### ISSUE TITLE
Brizy Local: User is not able to cancel the image upload dialog box  

### ISSUE THREAD

**Issue by bagrinsergiu** [EasyBrizy/Brizy-Local-Editor#91]
https://github.com/bagrinsergiu/blox-editor/issues/21951

It is very important for us.
User is not able to cancel the image upload dialog box and also when upload is cancelled pop up keeps on showing up:
The same has been shown in gif file below:
https://app.birdeatsbug.com/sessions/gfXwI-3SKRSqRLya2Z36BPlvAvhdOeBQkV9L5SKmCbVF

**Comment by maxval1** [comment]
Brizy builder doesn't answer what kind of media uploader it uses, the problem given is on the partner side.
For more information on how to use you can see https://github.com/EasyBrizy/Brizy-Local-Editor/blob/master/packages/core/docs/cdn.MD#api-parameters

Every time the handler function is used it must be called or `response()` or `reject()` otherwise the builder will be in the wait state
